Company.create!([
  {company_name: "Tulip11111", branch_name: "Behala", ph_number: "8017578589.0", email: "Tathagata0330@gmail.com", web_site: "", vat_number: "123", cst_number: "123", trade_license_number: "123", drug_license_number: "123", registration_number: "123", authorized_sign_img: "/uploads/149935087851tulip.jpg", company_logo_img: "/uploads/149935090247tulip.jpg"}
])
Employee.create!([
  {name: "Tathagaya", company_id: 1, address: "653 sarsuna main road. Kolkata 61", voter_card_no: "1837463", aadhar_card_no: "18374638", pan_no: "1837463", date_of_joining: "2017-07-04", designation: "Ooooo", type_of_work: "Ooooo", job_desc: "Ooooo", terms: "Oooo", salary: "1.0", bank_name: "Fjdndbd", bank_acc_no: "19293763", ifsc_code: "1938373", phone_no: "8017578589", email: "Tathagata0330@gmail.com"}
])
EmployeeLeave.create!([
  {employee_id: 1, leave_amount: 7, type_of_leave: "Casual", financial_year: 2017}
])
LeaveTransaction.create!([
  {employee_id: 1, employee_leave_id: 1, start_date: "2017-08-13", end_date: "2017-08-14", description: "Going to play cricket"}
])
Product.create!([
  {name: "Folitrax", description: "Used to treat cancer", product_type: "Medicine", packing: "NA", unit: "50.0", trading_price: "14.0", mrp: "16.0", hsn: "HSN01", batch: "B001", mfg_date: "12-Nov-2017", use_within: "6 months"}
])
RawMaterial.create!([
  {name: "DIGITOL", description: "", qty: "0.0", unit: "100 ml", hsn: "HSN001", gst_rate: "9"},
  {name: "MINADEX FORTE", description: "Chelated Iron and Mineral Powder with Vitamins and Phosphorus", qty: "0.0", unit: "100 gm", hsn: nil, gst_rate: nil},
  {name: "MINADEX FORTE", description: "Chelated Iron and Mineral Powder with Vitamins and Phosphorus", qty: "0.0", unit: "1 kg", hsn: nil, gst_rate: nil},
  {name: "MINADEX FORTE", description: "Chelated Iron and Mineral Powder with Vitamins and Phosphorus", qty: "0.0", unit: "500 gm", hsn: nil, gst_rate: nil},
  {name: "LIPOVET", description: "A Logical and Liver Friendly Combination to Boost Up Liver Function", qty: "0.0", unit: "100 ml", hsn: nil, gst_rate: nil},
  {name: "LIPOVET", description: "A Logical and Liver Friendly Combination to Boost Up Liver Function", qty: "0.0", unit: "250 ml", hsn: nil, gst_rate: nil},
  {name: "LIPOVET", description: "A Logical and Liver Friendly Combination to Boost Up Liver Function", qty: "0.0", unit: "500 ml", hsn: nil, gst_rate: nil},
  {name: "VETLYTE-C", description: "Feed Supplement for Poultry and Dairy", qty: "0.0", unit: "100 ml", hsn: nil, gst_rate: nil},
  {name: "VETLYTE-C", description: "Feed Supplement for Poultry and Dairy", qty: "0.0", unit: "250 ml", hsn: nil, gst_rate: nil},
  {name: "VETLYTE-C", description: "Feed Supplement for Poultry and Dairy", qty: "0.0", unit: "500 ml", hsn: nil, gst_rate: nil},
  {name: "VETLYTE-C", description: "Feed Supplement for Poultry and Dairy", qty: "0.0", unit: "1 ltr", hsn: nil, gst_rate: nil},
  {name: "ZYMED-VET", description: "", qty: "0.0", unit: "100 ml", hsn: nil, gst_rate: nil},
  {name: "ZYMED-VET", description: "", qty: "0.0", unit: "250 ml", hsn: nil, gst_rate: nil},
  {name: "ZYMED-VET", description: "", qty: "0.0", unit: "500 ml", hsn: nil, gst_rate: nil},
  {name: "ZYMED-VET", description: "", qty: "0.0", unit: "1 ltr", hsn: nil, gst_rate: nil},
  {name: "V-GEL", description: "Anti-Blotting Feed supplement for Livestock", qty: "0.0", unit: "100 ml", hsn: nil, gst_rate: nil},
  {name: "V-GEL", description: "Anti-Blotting Feed supplement for Livestock", qty: "0.0", unit: "250 ml", hsn: nil, gst_rate: nil},
  {name: "V-GEL", description: "Anti-Blotting Feed supplement for Livestock", qty: "0.0", unit: "500 ml", hsn: nil, gst_rate: nil},
  {name: "V-GEL", description: "Anti-Blotting Feed supplement for Livestock", qty: "0.0", unit: "1 ltr", hsn: nil, gst_rate: nil},
  {name: "VITUS-ADEC", description: "", qty: "0.0", unit: "100 ml", hsn: nil, gst_rate: nil},
  {name: "VITUS-ADEC", description: "", qty: "0.0", unit: "250 ml", hsn: nil, gst_rate: nil},
  {name: "VITUS-ADEC", description: "", qty: "0.0", unit: "500 ml", hsn: nil, gst_rate: nil},
  {name: "VITUS-ADEC", description: "", qty: "0.0", unit: "1 ltr", hsn: nil, gst_rate: nil},
  {name: "CALCI-GOLD", description: "Double strength Calcium and Phosphorus with Vitamin A, D3, B12, and Zinc fortified with herb extracts.", qty: "0.0", unit: "100 ml", hsn: nil, gst_rate: nil},
  {name: "CALCI-GOLD", description: "Double strength Calcium and Phosphorus with Vitamin A, D3, B12, and Zinc fortified with herb extracts.", qty: "0.0", unit: "250 ml", hsn: nil, gst_rate: nil},
  {name: "CALCI-GOLD", description: "Double strength Calcium and Phosphorus with Vitamin A, D3, B12, and Zinc fortified with herb extracts.", qty: "0.0", unit: "500 ml", hsn: nil, gst_rate: nil},
  {name: "CALCI-GOLD", description: "Double strength Calcium and Phosphorus with Vitamin A, D3, B12, and Zinc fortified with herb extracts.", qty: "0.0", unit: "1 ltr", hsn: nil, gst_rate: nil},
  {name: "MINADEX", description: "Mineral powder for poultry and dairy use.", qty: "0.0", unit: "100 gm", hsn: nil, gst_rate: nil},
  {name: "MINADEX", description: "Mineral powder for poultry and dairy use.", qty: "0.0", unit: "500 gm", hsn: nil, gst_rate: nil},
  {name: "MINADEX", description: "Mineral powder for poultry and dairy use.", qty: "0.0", unit: "1 kg", hsn: nil, gst_rate: nil},
  {name: "CV-10", description: "CV-10 is a useful antifungal supplement to prevent fungal diseases in broilers.", qty: "0.0", unit: "100 ml", hsn: nil, gst_rate: nil},
  {name: "CV-10", description: "CV-10 is a useful antifungal supplement to prevent fungal diseases in broilers.", qty: "0.0", unit: "1 ltr", hsn: nil, gst_rate: nil},
  {name: "CV-10", description: "CV-10 is a useful antifungal supplement to prevent fungal diseases in broilers.", qty: "0.0", unit: "500 ml", hsn: nil, gst_rate: nil},
  {name: "CV-10", description: "CV-10 is a useful antifungal supplement to prevent fungal diseases in broilers.", qty: "0.0", unit: "250 ml", hsn: nil, gst_rate: nil},
  {name: "LACTOCAL", description: "Specially formulized for better milk production.", qty: "0.0", unit: "100 ml", hsn: nil, gst_rate: nil},
  {name: "LACTOCAL", description: "Specially formulized for better milk production.", qty: "0.0", unit: "250 ml", hsn: nil, gst_rate: nil},
  {name: "LACTOCAL", description: "Specially formulized for better milk production.", qty: "0.0", unit: "500 ml", hsn: nil, gst_rate: nil},
  {name: "LACTOCAL", description: "Specially formulized for better milk production.", qty: "0.0", unit: "1 ltr", hsn: nil, gst_rate: nil},
  {name: "CALCIBIRD", description: "Essential calcium supplement for ornamental birds", qty: "0.0", unit: "100 ml", hsn: nil, gst_rate: nil},
  {name: "FURAZIN - B", description: "Anti-diarrheal supplement for ornamental birds.", qty: "0.0", unit: "100 ml", hsn: nil, gst_rate: nil},
  {name: "AQUALITE", description: "Aquaculture grade Zeolite", qty: "0.0", unit: "1 kg", hsn: nil, gst_rate: nil},
  {name: "AQUADIN", description: "Aquaculture grade 20% Iodine solution", qty: "0.0", unit: "100 ml", hsn: nil, gst_rate: nil},
  {name: "MULTIMIN-DS", description: "Mineral powder for aqua-culture use", qty: "0.0", unit: "500 gm", hsn: nil, gst_rate: nil},
  {name: "MULTIMIN-DS", description: "Mineral powder for aqua-culture use", qty: "0.0", unit: "1 kg", hsn: nil, gst_rate: nil},
  {name: "FISHCAL-DS", description: "Multivitamin mineral supplement for aquaculture use", qty: "0.0", unit: "100 ml", hsn: nil, gst_rate: nil},
  {name: "FISHCAL-DS", description: "Multivitamin mineral supplement for aquaculture use", qty: "0.0", unit: "500 ml", hsn: nil, gst_rate: nil},
  {name: "FISHCAL-DS", description: "Multivitamin mineral supplement for aquaculture use", qty: "0.0", unit: "1 ltr", hsn: nil, gst_rate: nil},
  {name: "F-CURE", description: "Aquaculture grade water purifier", qty: "0.0", unit: "500 gm", hsn: nil, gst_rate: nil},
  {name: "F-CURE", description: "Aquaculture grade water purifier", qty: "0.0", unit: "1 kg", hsn: nil, gst_rate: nil},
  {name: "LIVOFISH", description: "Liver and digestive booster for fish", qty: "0.0", unit: "0", hsn: nil, gst_rate: nil},
  {name: "DIGITOL", description: "", qty: "0.0", unit: "500 ml", hsn: nil, gst_rate: nil},
  {name: "DIGITOL", description: "", qty: "0.0", unit: "1 ltr", hsn: nil, gst_rate: nil},
  {name: "DEODAR 50 POWDER", description: "Yucca powder to prevent ammonia", qty: "0.0", unit: "500 gm", hsn: nil, gst_rate: nil},
  {name: "DEODAR 50 POWDER", description: "Yucca powder to prevent ammonia", qty: "0.0", unit: "1 kg", hsn: nil, gst_rate: nil},
  {name: "DEODAR 50 LIQUID", description: "Yucca powder to prevent ammonia", qty: "0.0", unit: "500 ml", hsn: nil, gst_rate: nil},
  {name: "DEODAR 50 LIQUID", description: "Yucca powder to prevent ammonia", qty: "0.0", unit: "1 ltr", hsn: nil, gst_rate: nil},
  {name: "AQUA GEL", description: "Protein Based Binder Gel", qty: "0.0", unit: "1 ltr", hsn: nil, gst_rate: nil},
  {name: "AQUA GEL", description: "Protein Based Binder Gel", qty: "0.0", unit: "5 ltr", hsn: nil, gst_rate: nil},
  {name: "AQUA GEL", description: "Protein Based Binder Gel", qty: "0.0", unit: "20 ltr", hsn: nil, gst_rate: nil},
  {name: "BROMINATE PLUS", description: "Brominated compound 6.2%", qty: "0.0", unit: "1 ltr", hsn: nil, gst_rate: nil},
  {name: "BROMINATE PLUS", description: "Brominated compound 6.2%", qty: "0.0", unit: "5 ltr", hsn: nil, gst_rate: nil},
  {name: "PS PLUS", description: "Liquid Probiotic", qty: "0.0", unit: "5 ltr", hsn: nil, gst_rate: nil},
  {name: "PS PLUS", description: "Liquid Probiotic", qty: "0.0", unit: "20 ltr", hsn: nil, gst_rate: nil},
  {name: "GEOPOND", description: "Bottom soil degradation probiotics for aquaculture ponds with Probiotic", qty: "0.0", unit: "10 kg", hsn: nil, gst_rate: nil},
  {name: "STARGEL", description: "Binder Gel ", qty: "0.0", unit: "1 ltr", hsn: nil, gst_rate: nil},
  {name: "STARGEL", description: "Binder Gel ", qty: "0.0", unit: "5 ltr", hsn: nil, gst_rate: nil},
  {name: "STARGEL", description: "Binder Gel ", qty: "0.0", unit: "20 ltr", hsn: nil, gst_rate: nil},
  {name: "PROSOIL", description: "Water and soil probiotic", qty: "0.0", unit: "500 gm", hsn: nil, gst_rate: nil},
  {name: "PROSOIL", description: "Water and soil probiotic", qty: "0.0", unit: "1 kg", hsn: nil, gst_rate: nil},
  {name: "Calendula", description: "Works for cuts", qty: "0.0", unit: "0", hsn: nil, gst_rate: nil},
  {name: "DORAISE POWDER", description: "A powerful dissolved oxygen improver and stress reliever", qty: "0.0", unit: "500 gm", hsn: nil, gst_rate: nil},
  {name: "DORAISE POWDER", description: "A powerful dissolved oxygen improver and stress reliever", qty: "0.0", unit: "1 kg", hsn: nil, gst_rate: nil},
  {name: "DORAISE TABLET", description: "Oxygen generator tablet and dissolved oxygen improver.", qty: "0.0", unit: "500 gm", hsn: nil, gst_rate: nil},
  {name: "DORAISE TABLET", description: "Oxygen generator tablet and dissolved oxygen improver.", qty: "0.0", unit: "1 kg", hsn: nil, gst_rate: nil},
  {name: "PLANKTOZEN", description: "Planktozen is a perfect formulation of Probiotics, Chelated Minerals and Vitamins, helps in moulting and growth", qty: "0.0", unit: "1 kg", hsn: nil, gst_rate: nil},
  {name: "AQUAMIN MAX", description: "Aquaculture special Mineral Complex", qty: "0.0", unit: "25 kg", hsn: nil, gst_rate: nil},
  {name: "PHYTOBOOST DS", description: "Liquid mineral with probiotic, enhance plankton growth", qty: "0.0", unit: "1 ltr", hsn: nil, gst_rate: nil},
  {name: "PROLAC GR", description: "Concentrated water and soil probiotic", qty: "0.0", unit: "5 kg", hsn: nil, gst_rate: nil},
  {name: "PROLAC GR", description: "Concentrated water and soil probiotic", qty: "0.0", unit: "50 kg", hsn: nil, gst_rate: nil},
  {name: "PROLAC HD POWDER", description: "Highly concentrated probiotic with enzymes for aquaculture ponds", qty: "0.0", unit: "100 gm", hsn: nil, gst_rate: nil},
  {name: "PROLAC HD POWDER", description: "Highly concentrated probiotic with enzymes for aquaculture ponds", qty: "0.0", unit: "500 gm", hsn: nil, gst_rate: nil},
  {name: "GEOMAX GR", description: "Granulated Zeolite for aquaculture ponds ", qty: "0.0", unit: "20 kg", hsn: nil, gst_rate: nil},
  {name: "BOOST-UP", description: "Growth promoter and bodyweight enhancer of shrimps", qty: "0.0", unit: "500 gm", hsn: nil, gst_rate: nil},
  {name: "VIROKILL", description: "Antiviral Compound that prevent viral load in aquaculture pond", qty: "0.0", unit: "500 gm", hsn: nil, gst_rate: nil},
  {name: "GASS-OFF", description: "Aquaculture grade toxic gas absorbent", qty: "0.0", unit: "500 gm", hsn: nil, gst_rate: nil},
  {name: "GASS-OFF", description: "Aquaculture grade toxic gas absorbent", qty: "0.0", unit: "1 ltr", hsn: nil, gst_rate: nil},
  {name: "GASS-OFF", description: "Aquaculture grade toxic gas absorbent", qty: "0.0", unit: "5 ltr", hsn: nil, gst_rate: nil},
  {name: "ZOOTHANET", description: "Concentrated anti-protozoal liquid for aquaculture.", qty: "0.0", unit: "100 ml", hsn: nil, gst_rate: nil},
  {name: "ZOOTHANET", description: "Concentrated anti-protozoal liquid for aquaculture.", qty: "0.0", unit: "500 ml", hsn: nil, gst_rate: nil},
  {name: "CRAMPNEX", description: "For prevention of body cramp disease in Vannamei shrimps", qty: "0.0", unit: "10 kg", hsn: nil, gst_rate: nil},
  {name: "SODAMIN MAX", description: "Aqua-culture grade Mineral Powder", qty: "0.0", unit: "25 kg", hsn: nil, gst_rate: nil},
  {name: "MAXMIN VM", description: "Special mineral supplement for Vannamei shrimps", qty: "0.0", unit: "0", hsn: nil, gst_rate: nil},
  {name: "CALMIN - P", description: "Moult inducer, Hardness reducer, Soft-shell preventer.", qty: "0.0", unit: "25 kg", hsn: nil, gst_rate: nil},
  {name: "VANNAGUT GEL", description: "A highly effective gut improver in shrimps", qty: "0.0", unit: "1 ltr", hsn: nil, gst_rate: nil},
  {name: "VANNAGUT POWDER", description: "A highly effective gut improver in shrimps", qty: "0.0", unit: "500 gm", hsn: nil, gst_rate: nil},
  {name: "BENZODINE", description: "PVP Iodine\r\nBenzalkonium Chloride (BKC)\r\nFormaldehyde\r\n", qty: "0.0", unit: "1 ltr", hsn: nil, gst_rate: nil},
  {name: "OXYFRESH", description: "Oxygen generator & Toxin binder powder.", qty: "0.0", unit: "10 kg", hsn: nil, gst_rate: nil},
  {name: "TOXINATE TABLET", description: "TOXINET TABLET is a highly formulated ammonia reducer with advanced technology for aquaculture ponds.", qty: "0.0", unit: "500 gm", hsn: nil, gst_rate: nil},
  {name: "YEAST AQUA", description: "Aquaculture grade yeast ", qty: "0.0", unit: "1 kg", hsn: nil, gst_rate: nil},
  {name: "YUCCA80 LIQUID", description: "Yucca schidigera 80%, Aloevera with probiotics", qty: "0.0", unit: "500 gm", hsn: nil, gst_rate: nil},
  {name: "YUCCA80 LIQUID", description: "Yucca schidigera 80%, Aloevera with probiotics", qty: "0.0", unit: "1 kg", hsn: nil, gst_rate: nil},
  {name: "YUCCA80 LIQUID", description: "Yucca schidigera 80%, Aloevera with probiotics", qty: "0.0", unit: "500 ml", hsn: nil, gst_rate: nil},
  {name: "YUCCA80 LIQUID", description: "Yucca schidigera 80%, Aloevera with probiotics", qty: "0.0", unit: "1 ltr", hsn: nil, gst_rate: nil},
  {name: "LUB CLEAN", description: "Elemental copper", qty: "0.0", unit: "1 ltr", hsn: nil, gst_rate: nil},
  {name: "NUTRINA", description: "Total nutritional supplement for Aquaculture", qty: "0.0", unit: "1 kg", hsn: nil, gst_rate: nil},
  {name: "ASCORMIN C", description: "Ascorbic acid and Vitamin E\r\n", qty: "0.0", unit: "1 kg", hsn: nil, gst_rate: nil}
])
User.create!([
  {name: "Sutirtho", email: "sutirtho.sen.90@gmail.com", password_digest: "$2a$10$LtfsWyiTbPpxb1rpTZl5Ie1s2MUnkOCiwxEiuJgDls3EhJ63JopIW"}
])
